name: axon_ivy
description: A new Flutter project.
version: 2.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

  cupertino_icons: ^1.0.2

  # For Networking
  dio: ^5.4.0

  # For Assets
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_gen: ^5.3.2

  # For Model
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  shared_preferences: ^2.3.3
  get_it: ^7.6.4
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1
  easy_localization: ^3.0.3
  device_preview: ^1.2.0
  package_info_plus: ^8.0.0
  injectable: ^2.3.2
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  bot_toast: ^4.1.3
  flutter_spinkit: ^5.2.0
  mobile_scanner: ^6.0.0
  cached_network_image: ^3.3.1
  crypto: ^3.0.3
  flutter_inappwebview: ^6.1.5

  file_picker: ^8.1.6
  image_picker: ^1.1.2
  path: ^1.9.0
  flutter_slidable: ^3.1.1
  font_awesome_flutter: ^10.7.0
  connectivity_plus: ^6.0.3
  flutter_screenutil: ^5.9.0
  open_filex: ^4.7.0
  timeago: ^3.6.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
    # For Analyzer
  flutter_lints: ^3.0.1

  # For Builder
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  hive_generator: ^2.0.1

  # For Model
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.5
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

  assets:
    outputs:
      class_name: AppAssets

  fonts:
    outputs:
      class_name: AppFontFamily

  colors:
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

dependency_overrides:
  win32: ^5.10.0
  flutter_plugin_android_lifecycle: ^2.0.22
  image_picker_android: ^0.8.12
  path_provider_android: ^2.2.12
  shared_preferences_android: ^2.3.3
  permission_handler_android: ^12.0.12
  sqflite: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/streamlines/
