name: axon_ivy
description: A new Flutter project.
version: 3.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

  cupertino_icons: ^1.0.8

  # For Networking
  dio: ^5.9.1

  # For Assets
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  flutter_gen: ^5.8.0

  # For Model
  freezed_annotation: ^3.1.0
  go_router: ^14.8.1
  shared_preferences: ^2.5.3
  get_it: ^9.2.0
  fpdart: ^1.2.0
  pretty_dio_logger: ^1.4.0
  internet_connection_checker: ^3.0.1
  easy_localization: ^3.0.7
  device_preview: ^1.2.0
  package_info_plus: ^8.2.1
  injectable: ^2.7.1+4
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  bot_toast: ^4.1.3
  flutter_spinkit: ^5.2.1
  mobile_scanner: ^7.0.1
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  flutter_inappwebview: ^6.1.5

  file_picker: ^10.1.5
  image_picker: ^1.1.2
  path: ^1.9.1
  flutter_slidable: ^3.1.1
  font_awesome_flutter: ^10.8.0
  connectivity_plus: ^6.1.4
  flutter_screenutil: ^5.9.3
  open_filex: ^4.7.0
  timeago: ^3.7.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  html: ^0.15.5
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
    # For Analyzer
  flutter_lints: ^5.0.0

  # For Builder
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.8.0
  hive_ce_generator: ^1.10.1

  # For Model
  freezed: ^3.2.5
  json_serializable: ^6.9.5
  injectable_generator: ^2.12.0
  retrofit_generator: ^10.2.1
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

  assets:
    outputs:
      class_name: AppAssets

  fonts:
    outputs:
      class_name: AppFontFamily

  colors:
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/streamlines/
